#ifndef __IMAGETOSOLIDTEXTUREPROJECTIONMETHODS__
#define __IMAGETOSOLIDTEXTUREPROJECTIONMETHODS__

enum ImageToSolidTextureProjectionMethods {
    PLANAR_MAP = 0,
    SPHERICAL_MAP = 1,
    CYLINDRICAL_MAP = 2,
    TORUS_MAP = 5
};

#endif
