#ifndef __VSDK_TOOLKIT_GUI_FEEDBACK_PARALLEL_PARALLELPROGRESSMONITORCOMMAND_H__
#define __VSDK_TOOLKIT_GUI_FEEDBACK_PARALLEL_PARALLELPROGRESSMONITORCOMMAND_H__

enum ParallelProgressMonitorCommand {
    INIT,
    PROCESS_NEXT_ELEMENT,
    FINISH
};

#endif
