package vitral.toolkits.geometry;

import java.util.Vector;
import net.java.games.jogl.GL;
import vitral.toolkits.common.Vertex;
import vitral.toolkits.common.Triangle;

/* Generated by Together */

public class Mesh {
    private Vector <Vertex> vertexes;
    private Vector <Triangle> triangles;

    public static double phong = 100;

    public Mesh()
    {
      vertexes = new Vector <Vertex> ();
      triangles = new Vector <Triangle> ();
    }

    public Mesh(Vector <Vertex> vertexes,Vector <Triangle> triangles)
    {
      this.vertexes = vertexes;
      this.triangles = triangles;
    }

    public Vector getTriangles()
    {
        return this.triangles;
    }

    public Vector getVertexes()
    {
        return this.vertexes;
    }

    public void setTriangles(Vector <Triangle> v)
    {
        this.triangles = v;
    }

    public void setVertexes(Vector <Vertex> v)
    {
        this.vertexes = v;
    }

    public void addVertex(Vertex vertex)
    {
      this.vertexes.add(vertex);
    }

    public void addTriangle(Triangle triangle)
    {
      this.triangles.add(triangle);
    }


    public Vertex getVertexAt(int index)
    {
      return (Vertex)this.vertexes.elementAt(index);
    }

    public Triangle getTriangleAt(int index)
    {
      return (Triangle)this.triangles.elementAt(index);
    }

    public void draw(GL gl)
    {
    for (int i = 0; i < this.triangles.size() ; i++ )
        {
          Triangle triangle = getTriangleAt(i);
          long p0 = triangle.getPoint0();
          long p1 = triangle.getPoint1();
          long p2 = triangle.getPoint2();
          Vertex v1 = getVertexAt((int)p0);
          Vertex v2 = getVertexAt((int)p1);
          Vertex v3 = getVertexAt((int)p2);
          gl.glColor3d(1.0,1.0,1.0);
          gl.glBegin(gl.GL_LINE_LOOP);
             v1.draw(gl);
             v2.draw(gl);
             v3.draw(gl);
          gl.glEnd();
        }
    }

    public String toString()
    {
      return ("Mesh > #Triangles:" + triangles.size() +  " - #Vertexes:" + vertexes.size()) ;
    }
}
