#include "vsdk/toolkit/render/opengl1/OpenGL1Api.h"
#include "java/util/ArrayList.txx"
#include "vsdk/toolkit/gui/viewport/Viewport.h"
#include "vsdk/toolkit/gui/viewport/ViewportSet.h"
#include "vsdk/toolkit/render/opengl1/OpenGL1ColoredPrimitiveRenderer.h"
#include "vsdk/toolkit/render/opengl1/OpenGL1ViewportSetRenderer.h"
#include "vsdk/toolkit/render/opengl1/OpenGL1ViewportWindow.h"
OpenGL1ViewportSetRenderer::OpenGL1ViewportSetRenderer(ViewportSet*s,OpenGL1LabelImageProvider*l,ViewRenderer*r):set(s),labels(l),renderer(r){}OpenGL1ViewportSetRenderer::~OpenGL1ViewportSetRenderer(){for(std::map<Viewport*,OpenGL1ViewportWindow*>::iterator i=windows.begin();i!=windows.end();++i)delete i->second;}ViewportSet*OpenGL1ViewportSetRenderer::getViewportSet()const{return set;}OpenGL1ViewportWindow*OpenGL1ViewportSetRenderer::getWindow(Viewport*v){if(!v)return 0;if(!windows[v])windows[v]=new OpenGL1ViewportWindow(set,v,labels);return windows[v];}OpenGL1ViewportWindow*OpenGL1ViewportSetRenderer::getSelectedWindow(){return getWindow(set->getSelectedViewport());}void OpenGL1ViewportSetRenderer::activate(Viewport*v){v->updatePixelArea(set->getSizeXInPixels(),set->getSizeYInPixels());glViewport(v->getPixelStartX(),v->getPixelStartY(),v->getPixelSizeX(),v->getPixelSizeY());}
void OpenGL1ViewportSetRenderer::drawBorder(Viewport*v){if(!v->isActive()||v->getBorder()<=0)return;double x0=2*v->getStartXPercent()-1,y0=2*v->getStartYPercent()-1,x1=x0+2*v->getSizeXPercent(),y1=y0+2*v->getSizeYPercent();float p[]={(float)x0,(float)y0,0,(float)x1,(float)y0,0,(float)x1,(float)y1,0,(float)x0,(float)y0,0,(float)x1,(float)y1,0,(float)x0,(float)y1,0};java::ArrayList<float>pa,ca;for(int i=0;i<18;i++)pa.add(p[i]);bool selected=set->isSelected(v);for(int i=0;i<6;i++){ca.add(selected?1:.21f);ca.add(selected?.96f:.25f);ca.add(selected?0:.29f);ca.add(1);}glDisable(GL_DEPTH_TEST);OpenGL1ColoredPrimitiveRenderer::draw(Matrix4x4d::identityMatrix(),GL_TRIANGLES,pa,ca);glEnable(GL_DEPTH_TEST);}
void OpenGL1ViewportSetRenderer::draw(bool full){const java::ArrayList<Viewport*>&v=set->getViewports();if(!full||set->countActiveViewports()!=1)for(long i=0;i<v.size();i++)drawBorder(v[i]);for(long i=0;i<v.size();i++){Viewport*x=v[i];if(!x->isActive())continue;if(full&&set->countActiveViewports()==1&&!set->isSelected(x))continue;activate(x);OpenGL1ViewportWindow*w=getWindow(x);if(w->isSelected())renderer->configureView(w);renderer->drawView(w);w->drawTitle();}}void OpenGL1ViewportSetRenderer::disposeGlResources(){for(std::map<Viewport*,OpenGL1ViewportWindow*>::iterator i=windows.begin();i!=windows.end();++i)i->second->disposeGlResources();}void OpenGL1ViewportSetRenderer::invalidateGlResources(){for(std::map<Viewport*,OpenGL1ViewportWindow*>::iterator i=windows.begin();i!=windows.end();++i)i->second->invalidateGlResources();}
