import { PresentationElement } from "./PresentationElement.js";

/**
Key press or release, as delivered to the interaction techniques of vitral.

`unicodeId` is a Java `char`: it holds one UTF-16 code unit (a number, as
`String.charCodeAt` gives it), or `KEY_NONE` when the key produces no
character. `keycode` is one of the `KEY_*` constants and `modifierMask` a
combination of the `MASK_*` ones.
*/
export class KeyEvent extends PresentationElement {
    public keycode: number;
    public unicodeId: number;
    public modifierMask: number;

    public static readonly MASK_CTRL = 0x0001;
    public static readonly MASK_LCTRL = 0x0002;
    public static readonly MASK_RCTRL = 0x0004;
    public static readonly MASK_ALT = 0x0008;
    public static readonly MASK_LALT = 0x0010;
    public static readonly MASK_RALT = 0x0020;
    public static readonly MASK_ALTGR = 0x0040;
    public static readonly MASK_SHIFT = 0x0080;
    public static readonly MASK_LSHIFT = 0x0100;
    public static readonly MASK_RSHIFT = 0x0200;
    public static readonly MASK_WINKEY = 0x0400;
    public static readonly KEY_NONE = 0x0000;
    public static readonly KEY_A = 0x0001;
    public static readonly KEY_B = 0x0002;
    public static readonly KEY_C = 0x0003;
    public static readonly KEY_D = 0x0004;
    public static readonly KEY_E = 0x0005;
    public static readonly KEY_F = 0x0006;
    public static readonly KEY_G = 0x0007;
    public static readonly KEY_H = 0x0008;
    public static readonly KEY_I = 0x0009;
    public static readonly KEY_J = 0x000A;
    public static readonly KEY_K = 0x000B;
    public static readonly KEY_L = 0x000C;
    public static readonly KEY_M = 0x000D;
    public static readonly KEY_N = 0x000E;
    public static readonly KEY_O = 0x000F;
    public static readonly KEY_P = 0x0010;
    public static readonly KEY_Q = 0x0011;
    public static readonly KEY_R = 0x0012;
    public static readonly KEY_S = 0x0013;
    public static readonly KEY_T = 0x0014;
    public static readonly KEY_U = 0x0015;
    public static readonly KEY_V = 0x0016;
    public static readonly KEY_W = 0x0017;
    public static readonly KEY_X = 0x0018;
    public static readonly KEY_Y = 0x0019;
    public static readonly KEY_Z = 0x001A;
    public static readonly KEY_a = 0x001B;
    public static readonly KEY_b = 0x001C;
    public static readonly KEY_c = 0x001D;
    public static readonly KEY_d = 0x001E;
    public static readonly KEY_e = 0x001F;
    public static readonly KEY_f = 0x0020;
    public static readonly KEY_g = 0x0021;
    public static readonly KEY_h = 0x0022;
    public static readonly KEY_i = 0x0023;
    public static readonly KEY_j = 0x0024;
    public static readonly KEY_k = 0x0025;
    public static readonly KEY_l = 0x0026;
    public static readonly KEY_m = 0x0027;
    public static readonly KEY_n = 0x0028;
    public static readonly KEY_o = 0x0029;
    public static readonly KEY_p = 0x002A;
    public static readonly KEY_q = 0x002B;
    public static readonly KEY_r = 0x002C;
    public static readonly KEY_s = 0x002D;
    public static readonly KEY_t = 0x002E;
    public static readonly KEY_u = 0x002F;
    public static readonly KEY_v = 0x0030;
    public static readonly KEY_w = 0x0031;
    public static readonly KEY_x = 0x0032;
    public static readonly KEY_y = 0x0033;
    public static readonly KEY_z = 0x0034;
    public static readonly KEY_0 = 0x0035;
    public static readonly KEY_1 = 0x0036;
    public static readonly KEY_2 = 0x0037;
    public static readonly KEY_3 = 0x0038;
    public static readonly KEY_4 = 0x0039;
    public static readonly KEY_5 = 0x003A;
    public static readonly KEY_6 = 0x003B;
    public static readonly KEY_7 = 0x003C;
    public static readonly KEY_8 = 0x003D;
    public static readonly KEY_9 = 0x003E;
    public static readonly KEY_NUM0 = 0x003F;
    public static readonly KEY_NUM1 = 0x0040;
    public static readonly KEY_NUM2 = 0x0041;
    public static readonly KEY_NUM3 = 0x0042;
    public static readonly KEY_NUM4 = 0x0043;
    public static readonly KEY_NUM5 = 0x0044;
    public static readonly KEY_NUM6 = 0x0045;
    public static readonly KEY_NUM7 = 0x0046;
    public static readonly KEY_NUM8 = 0x0047;
    public static readonly KEY_NUM9 = 0x0048;
    public static readonly KEY_F1 = 0x0049;
    public static readonly KEY_F2 = 0x004A;
    public static readonly KEY_F3 = 0x004B;
    public static readonly KEY_F4 = 0x004C;
    public static readonly KEY_F5 = 0x004D;
    public static readonly KEY_F6 = 0x004E;
    public static readonly KEY_F7 = 0x004F;
    public static readonly KEY_F8 = 0x0050;
    public static readonly KEY_F9 = 0x0051;
    public static readonly KEY_F10 = 0x0052;
    public static readonly KEY_F11 = 0x0053;
    public static readonly KEY_F12 = 0x0054;
    public static readonly KEY_ESC = 0x0055;
    public static readonly KEY_PRINTSCREEN = 0x0056;
    public static readonly KEY_BACKSPACE = 0x0057;
    public static readonly KEY_INSERT = 0x0058;
    public static readonly KEY_DELETE = 0x0059;
    public static readonly KEY_PAGEUP = 0x005A;
    public static readonly KEY_PAGEDOWN = 0x005B;
    public static readonly KEY_HOME = 0x005C;
    public static readonly KEY_END = 0x005D;
    public static readonly KEY_SPACE = 0x005E;
    public static readonly KEY_LSHIFT = 0x005F;
    public static readonly KEY_RSHIFT = 0x0060;
    public static readonly KEY_LALT = 0x0061;
    public static readonly KEY_RALT = 0x0062;
    public static readonly KEY_ALTGR = 0x0063;
    public static readonly KEY_LCTRL = 0x0064;
    public static readonly KEY_RCTRL = 0x0065;
    public static readonly KEY_UP = 0x0066;
    public static readonly KEY_DOWN = 0x0067;
    public static readonly KEY_LEFT = 0x0068;
    public static readonly KEY_RIGHT = 0x0069;
    public static readonly KEY_NUMSLASH = 0x006A;
    public static readonly KEY_NUMASTERISK = 0x006B;
    public static readonly KEY_NUMMINUS = 0x006C;
    public static readonly KEY_NUMPLUS = 0x006D;
    public static readonly KEY_NUMLOCK = 0x006E;
    public static readonly KEY_NUMENTER = 0x006F;
    public static readonly KEY_ENTER = 0x0070;
    public static readonly KEY_CAPSLOCK = 0x0071;
    public static readonly KEY_TAB = 0x0072;
    public static readonly KEY_COMMA = 0x0073;
    public static readonly KEY_PERIOD = 0x0074;
    public static readonly KEY_NUMPERIOD = 0x0075;
    public static readonly KEY_EQUALS = 0x0076;
    public static readonly KEY_MINUS = 0x0077;

    public constructor() {
        super();
        this.keycode = KeyEvent.KEY_NONE;
        this.unicodeId = KeyEvent.KEY_NONE;
        this.modifierMask = 0;
    }

    /**
    @param character a string whose first UTF-16 code unit is wanted
    @return the code unit, as Java's `char` literal of the same character
    */
    public static charCode(character: string): number {
        return character.charCodeAt(0);
    }

    public static getKeyName(key: number): string {
        let msg = "KEY_NONE";
        switch (key) {
            case KeyEvent.KEY_A: msg = "KEY_A"; break;
            case KeyEvent.KEY_B: msg = "KEY_B"; break;
            case KeyEvent.KEY_C: msg = "KEY_C"; break;
            case KeyEvent.KEY_D: msg = "KEY_D"; break;
            case KeyEvent.KEY_E: msg = "KEY_E"; break;
            case KeyEvent.KEY_F: msg = "KEY_F"; break;
            case KeyEvent.KEY_G: msg = "KEY_G"; break;
            case KeyEvent.KEY_H: msg = "KEY_H"; break;
            case KeyEvent.KEY_I: msg = "KEY_I"; break;
            case KeyEvent.KEY_J: msg = "KEY_J"; break;
            case KeyEvent.KEY_K: msg = "KEY_K"; break;
            case KeyEvent.KEY_L: msg = "KEY_L"; break;
            case KeyEvent.KEY_M: msg = "KEY_M"; break;
            case KeyEvent.KEY_N: msg = "KEY_N"; break;
            case KeyEvent.KEY_O: msg = "KEY_O"; break;
            case KeyEvent.KEY_P: msg = "KEY_P"; break;
            case KeyEvent.KEY_Q: msg = "KEY_Q"; break;
            case KeyEvent.KEY_R: msg = "KEY_R"; break;
            case KeyEvent.KEY_S: msg = "KEY_S"; break;
            case KeyEvent.KEY_T: msg = "KEY_T"; break;
            case KeyEvent.KEY_U: msg = "KEY_U"; break;
            case KeyEvent.KEY_V: msg = "KEY_V"; break;
            case KeyEvent.KEY_W: msg = "KEY_W"; break;
            case KeyEvent.KEY_X: msg = "KEY_X"; break;
            case KeyEvent.KEY_Y: msg = "KEY_Y"; break;
            case KeyEvent.KEY_Z: msg = "KEY_Z"; break;
            case KeyEvent.KEY_a: msg = "KEY_a"; break;
            case KeyEvent.KEY_b: msg = "KEY_b"; break;
            case KeyEvent.KEY_c: msg = "KEY_c"; break;
            case KeyEvent.KEY_d: msg = "KEY_d"; break;
            case KeyEvent.KEY_e: msg = "KEY_e"; break;
            case KeyEvent.KEY_f: msg = "KEY_f"; break;
            case KeyEvent.KEY_g: msg = "KEY_g"; break;
            case KeyEvent.KEY_h: msg = "KEY_h"; break;
            case KeyEvent.KEY_i: msg = "KEY_i"; break;
            case KeyEvent.KEY_j: msg = "KEY_j"; break;
            case KeyEvent.KEY_k: msg = "KEY_k"; break;
            case KeyEvent.KEY_l: msg = "KEY_l"; break;
            case KeyEvent.KEY_m: msg = "KEY_m"; break;
            case KeyEvent.KEY_n: msg = "KEY_n"; break;
            case KeyEvent.KEY_o: msg = "KEY_o"; break;
            case KeyEvent.KEY_p: msg = "KEY_p"; break;
            case KeyEvent.KEY_q: msg = "KEY_q"; break;
            case KeyEvent.KEY_r: msg = "KEY_r"; break;
            case KeyEvent.KEY_s: msg = "KEY_s"; break;
            case KeyEvent.KEY_t: msg = "KEY_t"; break;
            case KeyEvent.KEY_u: msg = "KEY_u"; break;
            case KeyEvent.KEY_v: msg = "KEY_v"; break;
            case KeyEvent.KEY_w: msg = "KEY_w"; break;
            case KeyEvent.KEY_x: msg = "KEY_x"; break;
            case KeyEvent.KEY_y: msg = "KEY_y"; break;
            case KeyEvent.KEY_z: msg = "KEY_z"; break;
            case KeyEvent.KEY_0: msg = "KEY_0"; break;
            case KeyEvent.KEY_1: msg = "KEY_1"; break;
            case KeyEvent.KEY_2: msg = "KEY_2"; break;
            case KeyEvent.KEY_3: msg = "KEY_3"; break;
            case KeyEvent.KEY_4: msg = "KEY_4"; break;
            case KeyEvent.KEY_5: msg = "KEY_5"; break;
            case KeyEvent.KEY_6: msg = "KEY_6"; break;
            case KeyEvent.KEY_7: msg = "KEY_7"; break;
            case KeyEvent.KEY_8: msg = "KEY_8"; break;
            case KeyEvent.KEY_9: msg = "KEY_9"; break;
            case KeyEvent.KEY_NUM0: msg = "KEY_NUM0"; break;
            case KeyEvent.KEY_NUM1: msg = "KEY_NUM1"; break;
            case KeyEvent.KEY_NUM2: msg = "KEY_NUM2"; break;
            case KeyEvent.KEY_NUM3: msg = "KEY_NUM3"; break;
            case KeyEvent.KEY_NUM4: msg = "KEY_NUM4"; break;
            case KeyEvent.KEY_NUM5: msg = "KEY_NUM5"; break;
            case KeyEvent.KEY_NUM6: msg = "KEY_NUM6"; break;
            case KeyEvent.KEY_NUM7: msg = "KEY_NUM7"; break;
            case KeyEvent.KEY_NUM8: msg = "KEY_NUM8"; break;
            case KeyEvent.KEY_NUM9: msg = "KEY_NUM9"; break;
            case KeyEvent.KEY_F1: msg = "KEY_F1"; break;
            case KeyEvent.KEY_F2: msg = "KEY_F2"; break;
            case KeyEvent.KEY_F3: msg = "KEY_F3"; break;
            case KeyEvent.KEY_F4: msg = "KEY_F4"; break;
            case KeyEvent.KEY_F5: msg = "KEY_F5"; break;
            case KeyEvent.KEY_F6: msg = "KEY_F6"; break;
            case KeyEvent.KEY_F7: msg = "KEY_F7"; break;
            case KeyEvent.KEY_F8: msg = "KEY_F8"; break;
            case KeyEvent.KEY_F9: msg = "KEY_F9"; break;
            case KeyEvent.KEY_F10: msg = "KEY_F10"; break;
            case KeyEvent.KEY_F11: msg = "KEY_F11"; break;
            case KeyEvent.KEY_F12: msg = "KEY_F12"; break;
            case KeyEvent.KEY_ESC: msg = "KEY_ESC"; break;
            case KeyEvent.KEY_PRINTSCREEN: msg = "KEY_PRINTSCREEN"; break;
            case KeyEvent.KEY_BACKSPACE: msg = "KEY_BACKSPACE"; break;
            case KeyEvent.KEY_INSERT: msg = "KEY_INSERT"; break;
            case KeyEvent.KEY_DELETE: msg = "KEY_DELETE"; break;
            case KeyEvent.KEY_PAGEUP: msg = "KEY_PAGEUP"; break;
            case KeyEvent.KEY_PAGEDOWN: msg = "KEY_PAGEDOWN"; break;
            case KeyEvent.KEY_HOME: msg = "KEY_HOME"; break;
            case KeyEvent.KEY_END: msg = "KEY_END"; break;
            case KeyEvent.KEY_SPACE: msg = "KEY_SPACE"; break;
            case KeyEvent.KEY_LSHIFT: msg = "KEY_LSHIFT"; break;
            case KeyEvent.KEY_RSHIFT: msg = "KEY_RSHIFT"; break;
            case KeyEvent.KEY_LALT: msg = "KEY_LALT"; break;
            case KeyEvent.KEY_RALT: msg = "KEY_RALT"; break;
            case KeyEvent.KEY_ALTGR: msg = "KEY_ALTGR"; break;
            case KeyEvent.KEY_LCTRL: msg = "KEY_LCTRL"; break;
            case KeyEvent.KEY_RCTRL: msg = "KEY_RCTRL"; break;
            case KeyEvent.KEY_UP: msg = "KEY_UP"; break;
            case KeyEvent.KEY_DOWN: msg = "KEY_DOWN"; break;
            case KeyEvent.KEY_LEFT: msg = "KEY_LEFT"; break;
            case KeyEvent.KEY_RIGHT: msg = "KEY_RIGHT"; break;
            case KeyEvent.KEY_NUMSLASH: msg = "KEY_NUMSLASH"; break;
            case KeyEvent.KEY_NUMASTERISK: msg = "KEY_NUMASTERISK"; break;
            case KeyEvent.KEY_NUMMINUS: msg = "KEY_NUMMINUS"; break;
            case KeyEvent.KEY_NUMPLUS: msg = "KEY_NUMPLUS"; break;
            case KeyEvent.KEY_NUMLOCK: msg = "KEY_NUMLOCK"; break;
            case KeyEvent.KEY_NUMENTER: msg = "KEY_NUMENTER"; break;
            case KeyEvent.KEY_ENTER: msg = "KEY_ENTER"; break;
            case KeyEvent.KEY_CAPSLOCK: msg = "KEY_CAPSLOCK"; break;
            case KeyEvent.KEY_TAB: msg = "KEY_TAB"; break;
            case KeyEvent.KEY_COMMA: msg = "KEY_COMMA"; break;
            case KeyEvent.KEY_PERIOD: msg = "KEY_PERIOD"; break;
            case KeyEvent.KEY_NUMPERIOD: msg = "KEY_NUMPERIOD"; break;
            case KeyEvent.KEY_EQUALS: msg = "KEY_EQUALS"; break;
            case KeyEvent.KEY_MINUS: msg = "KEY_MINUS"; break;
        }
        return msg;
    }
}
