/* Generated by Together */

package vsdk.toolkit.common;

public class Triangle {
  private int point0;
  private int point1;
  private int point2;

  private int vt0;
  private int vt1;
  private int vt2;

  /**
   * @directed
   * @supplierRole normal
   * @supplierCardinality 0..1
   * @clientCardinality 1
   * @link aggregation*/
  public Vector3D normal;

  /**
   *
   */
  public Triangle() {
  }

  /**
   *
   * @param point0 long
   * @param point1 long
   * @param point2 long
   */
  public Triangle(int point0, int point1, int point2) {
    this.point0 = point0;
    this.point1 = point1;
    this.point2 = point2;
  }

  public Triangle(int point0, int point1, int point2, int vt0, int vt1, int vt2) {
    this.point0 = point0;
    this.point1 = point1;
    this.point2 = point2;
    this.vt0 = vt0;
    this.vt1 = vt1;
    this.vt2 = vt2;
  }

  public String toString() {

    return "f < " + this.point0 + ", " + this.point1 + ", " +
        this.point2 + " >";
  }

  /**
   *
   * @return long
   */
  public int getPoint0() {
    return this.point0;
  }

  /**
   *
   * @return long
   */
  public int getPoint1() {
    return this.point1;
  }

  /**
   *
   * @return long
   */
  public int getPoint2() {
    return this.point2;
  }

public int getVt0()
  {
    return this.vt0;
  }

  public int getVt1()
  {
    return this.vt1;
  }

  public int getVt2()
  {
    return this.vt2;
  }


  /**
   *
   * @param point0 long
   */
  public void setPoint0(int point0) {
    this.point0 = point0;
  }

  /**
   *
   * @param point1 long
   */
  public void setPoint1(int point1) {
    this.point1 = point1;
  }

  /**
   *
   * @param point2 long
   */
  public void setPoint2(int point2) {
    this.point2 = point2;
  }

  public void setVt0(int vt0)
  {
    this.vt0 = vt0;
  }

  public void setVt1(int vt1)
  {
    this.vt1 = vt1;
  }

  public void setVt2(int vt2)
  {
    this.vt2 = vt2;
  }
}
