import { Vector3Dd } from "../../../common/linealAlgebra/Vector3Dd.js";
import { Containment } from "../../../processing/Containment.js";
import type { Image } from "../../../media/Image.js";
import type { SimpleMaterial } from "../../material/SimpleMaterial.js";
import { Ray } from "../element/Ray.js";
import { RayHit } from "../element/RayHit.js";
import { Triangle } from "../element/Triangle.js";
import { Vertex } from "../element/Vertex.js";
import { Surface } from "./Surface.js";
import { TriangleMeshGroup } from "./TriangleMeshGroup.js";

/** Indexed triangle mesh with optional vertex attributes and material spans. */
export class TriangleMesh extends Surface<Ray, RayHit> {
  private name = "default"; private vertexPositions: Float64Array | null = null; private vertexNormals: Float64Array | null = null; private vertexBinormals: Float64Array | null = null; private vertexTangents: Float64Array | null = null; private vertexColors: Float64Array | null = null; private vertexSelections: boolean[] | null = null; private vertexUvs: Float64Array | null = null; private triangleIndices: Int32Array | null = null; private triangleNormals: Float64Array | null = null; private incidentTrianglesPerVertexArray: number[][] | null = null; private materials: SimpleMaterial[] | null = null; private textures: Image[] | null = null; private textureRanges: number[][] | null = null; private materialRanges: number[][] | null = null; private intersectionTriangleIndex = -1;
  public getName(): string { return this.name; } public setName(name: string): void { this.name = name; }
  public override clone(other?: TriangleMesh): TriangleMesh | void { if (other !== undefined) { this.copyFrom(other); return; } const copy = new TriangleMesh(); copy.copyFrom(this); return copy; }
  private copyFrom(other: TriangleMesh): void { this.name = other.name; this.vertexPositions = other.vertexPositions?.slice() ?? null; this.vertexNormals = other.vertexNormals?.slice() ?? null; this.vertexBinormals = other.vertexBinormals?.slice() ?? null; this.vertexTangents = other.vertexTangents?.slice() ?? null; this.vertexColors = other.vertexColors?.slice() ?? null; this.vertexSelections = other.vertexSelections?.slice() ?? null; this.vertexUvs = other.vertexUvs?.slice() ?? null; this.triangleIndices = other.triangleIndices?.slice() ?? null; this.triangleNormals = other.triangleNormals?.slice() ?? null; this.materials = other.materials?.slice() ?? null; this.textures = other.textures?.slice() ?? null; this.textureRanges = other.textureRanges?.map(x => x.slice()) ?? null; this.materialRanges = other.materialRanges?.map(x => x.slice()) ?? null; this.calculateNormals(); }
  public initVertexPositionsArray(n: number): void { this.vertexPositions = new Float64Array(n * 3); }
  public initVertexNormalsArray(): void { this.vertexNormals = new Float64Array(this.getNumVertices() * 3); }
  public initVertexBinormalsArray(): void { this.vertexBinormals = new Float64Array(this.getNumVertices() * 3); }
  public initVertexTangentsArray(): void { this.vertexTangents = new Float64Array(this.getNumVertices() * 3); }
  public initVertexColorsArray(): void { this.vertexColors = new Float64Array(this.getNumVertices() * 3); }
  public initVertexUvsArray(): void { this.vertexUvs = new Float64Array(this.getNumVertices() * 2); }
  public initIncidentTrianglesPerVertexArray(): void { this.incidentTrianglesPerVertexArray = Array.from({ length: this.getNumVertices() }, () => []); }
  public initTriangleArrays(n: number): void { this.triangleIndices = new Int32Array(n * 3); this.triangleNormals = new Float64Array(n * 3); }
  public detachColors(): void { this.vertexColors = null; } public detachNormals(): void { this.vertexNormals = null; } public detachUvs(): void { this.vertexUvs = null; }
  public setVertexes(vertices: Vertex[], withNormals = true, withBinormals = false, withTangents = false, withUvs = false): void { this.initVertexPositionsArray(vertices.length); if (withNormals) this.initVertexNormalsArray(); if (withBinormals) this.initVertexBinormalsArray(); if (withTangents) this.initVertexTangentsArray(); if (withUvs) this.initVertexUvsArray(); for (let i = 0; i < vertices.length; i++) this.writeVertex(i, vertices[i]!); }
  public setTriangles(triangles: Triangle[]): void { this.initTriangleArrays(triangles.length); for (let i = 0; i < triangles.length; i++) this.setTriangleAt(i, triangles[i]!); }
  public getVertexAt(i: number, vertex: Vertex): void { this.assertVertex(i); vertex.setPosition(this.position(i)); if (this.vertexNormals !== null) vertex.setNormal(this.vector(this.vertexNormals, i)); if (this.vertexBinormals !== null) vertex.setBinormal(this.vector(this.vertexBinormals, i)); if (this.vertexTangents !== null) vertex.setTangent(this.vector(this.vertexTangents, i)); if (this.vertexUvs !== null) { vertex.setU(this.vertexUvs[i * 2]!); vertex.setV(this.vertexUvs[i * 2 + 1]!); } }
  public setVertexAt(i: number, vertex: Vertex): void { this.assertVertex(i); this.writeVertex(i, vertex); }
  public setTriangleAt(i: number, triangle: Triangle): void { if (this.triangleIndices === null || i < 0 || i >= this.getNumTriangles()) throw new RangeError("Triangle index out of bounds"); const indices = [triangle.getPoint0(), triangle.getPoint1(), triangle.getPoint2()]; for (const index of indices) this.assertVertex(index); this.triangleIndices.set(indices, i * 3); if (this.triangleNormals !== null) this.setVector(this.triangleNormals, i, triangle.getNormal()); }
  public getNumVertices(): number { return this.vertexPositions?.length === undefined ? 0 : this.vertexPositions.length / 3; } public getNumTriangles(): number { return this.triangleIndices?.length === undefined ? 0 : this.triangleIndices.length / 3; }
  public getVertexSelections(): boolean[] { return this.vertexSelections ??= Array.from({ length: this.getNumVertices() }, () => false); }
  public getVertexPositions(): Float64Array | null { return this.vertexPositions; } public getVertexNormals(): Float64Array | null { return this.vertexNormals; } public getVertexBinormals(): Float64Array | null { return this.vertexBinormals; } public getVertexTangents(): Float64Array | null { return this.vertexTangents; } public getVertexColors(): Float64Array | null { return this.vertexColors; } public getVertexUvs(): Float64Array | null { return this.vertexUvs; } public getTriangleIndexes(): Int32Array | null { return this.triangleIndices; } public getTriangleNormals(): Float64Array | null { return this.triangleNormals; }
  public getMaterials(): SimpleMaterial[] | null { return this.materials; } public setMaterials(x: SimpleMaterial[]): void { this.materials = x; } public getTextures(): Image[] | null { return this.textures; } public setTextures(x: Image[]): void { this.textures = x; } public getTextureAt(i: number): Image | undefined { return this.textures?.[i]; } public setTextureAt(i: number, x: Image): void { if (this.textures === null) throw new Error("Textures are not initialized"); this.textures[i] = x; }
  public getTextureRanges(): number[][] | null { return this.textureRanges; } public getTextureRangeAt(i: number): number[] | undefined { return this.textureRanges?.[i]; } public setTextureRanges(x: number[][]): void { this.textureRanges = x; } public getMaterialRanges(): number[][] | null { return this.materialRanges; } public getMaterialRangeAt(i: number): number[] | undefined { return this.materialRanges?.[i]; } public setMaterialRanges(x: number[][]): void { this.materialRanges = x; }
  public calculateNormals(): void { if (this.vertexPositions === null || this.triangleIndices === null) return; this.triangleNormals = new Float64Array(this.getNumTriangles() * 3); const sums = Array.from({ length: this.getNumVertices() }, () => new Vector3Dd()); this.initIncidentTrianglesPerVertexArray(); for (let i = 0; i < this.getNumTriangles(); i++) { const [a,b,c] = this.triangle(i); const normal = this.position(b).subtract(this.position(a)).crossProduct(this.position(c).subtract(this.position(a))).normalized(); this.setVector(this.triangleNormals, i, normal); for (const index of [a,b,c]) { sums[index] = sums[index]!.add(normal); this.incidentTrianglesPerVertexArray![index]!.push(i); } } this.initVertexNormalsArray(); for (let i = 0; i < sums.length; i++) this.setVector(this.vertexNormals!, i, sums[i]!.normalized()); }
  public reorientateNormals(): void { if (this.vertexNormals === null) return; for (let i = 0; i < this.getNumTriangles(); i++) { const [a,b,c] = this.triangle(i); const normal = this.position(b).subtract(this.position(a)).crossProduct(this.position(c).subtract(this.position(a))).normalized(); if (this.triangleNormals !== null) this.setVector(this.triangleNormals, i, normal); for (const index of [a,b,c]) { const n = this.vector(this.vertexNormals, index); if (normal.dotProduct(n) < 0) this.setVector(this.vertexNormals, index, n.multiply(-1)); } } }
  public doIntersectionInformation(): number { return this.intersectionTriangleIndex; }
  public doIntersectionFirstHit(ray: Ray, out: RayHit, triangleInformation?: Int32Array | number[]): boolean { let best: { index: number; t: number; point: Vector3Dd; normal: Vector3Dd } | null = null; for (let i = 0; i < this.getNumTriangles(); i++) { const [a,b,c] = this.triangle(i); const hit = Triangle.doIntersectionWithTriangle(ray, this.position(a), this.position(b), this.position(c)); if (hit !== null && (best === null || hit.getT() < best.t)) best = { index: i, t: hit.getT(), point: hit.getPoint(), normal: hit.getNormal() }; } if (best === null) { this.intersectionTriangleIndex = -1; if (triangleInformation !== undefined) triangleInformation[0] = -1; return false; } this.intersectionTriangleIndex = best.index; if (triangleInformation !== undefined) triangleInformation[0] = best.index; out.setRay(ray.withT(best.t)); out.p = new Vector3Dd(best.point); out.n = new Vector3Dd(best.normal).normalized(); out.t = new Vector3Dd(); out.u = 0; out.v = 0; this.interpolateTriangleData(best.index, out, ray.getDirection()); this.fillMaterialAndTexture(best.index, out); return true; }
  public override doExtraInformation(ray: Ray, t: number, out: RayHit): void { this.doIntersectionFirstHit(ray.withT(t), out); }
  public override doContainmentTest(point: Vector3Dd, tolerance: number): number { for (let i = 0; i < this.getNumTriangles(); i++) { const [a,b,c] = this.triangle(i); if (Triangle.containmentTest(this.position(a), this.position(b), this.position(c), point, tolerance) !== Containment.OUTSIDE) return Containment.LIMIT; } return Containment.OUTSIDE; }
  public getMinMax(): Float64Array { const result = new Float64Array([Infinity, Infinity, Infinity, -Infinity, -Infinity, -Infinity]); for (let i = 0; i < this.getNumVertices(); i++) { const p = this.position(i); result[0] = Math.min(result[0]!,p.x()); result[1] = Math.min(result[1]!,p.y()); result[2] = Math.min(result[2]!,p.z()); result[3] = Math.max(result[3]!,p.x()); result[4] = Math.max(result[4]!,p.y()); result[5] = Math.max(result[5]!,p.z()); } return result; }
  public exportToTriangleMeshGroup(): TriangleMeshGroup { return new TriangleMeshGroup([this]); }
  public compact(): void { if (this.vertexPositions === null || this.triangleIndices === null) return; const used = new Set<number>(); const valid: number[][] = []; for (let i = 0; i < this.getNumTriangles(); i++) { const triangle = this.triangle(i); if (triangle.every(index => index >= 0 && index < this.getNumVertices())) { valid.push(triangle); triangle.forEach(index => used.add(index)); } } const map = new Map<number, number>(); const vertices = [...used].sort((a,b) => a-b).map((old, next) => { map.set(old,next); return this.position(old); }); this.setVertexes(vertices.map(x => new Vertex(x)), false); this.initTriangleArrays(valid.length); valid.forEach((triangle,i) => this.triangleIndices!.set(triangle.map(x => map.get(x)!) , i*3)); this.calculateNormals(); }
  public removeSelectedVertices(): void { if (this.vertexSelections === null || this.triangleIndices === null) return; for (let i = 0; i < this.getNumTriangles(); i++) { const indices = this.triangle(i); if (indices.some(x => this.vertexSelections![x])) this.triangleIndices.set([-1,-1,-1], i*3); } this.vertexSelections = null; this.compact(); }
  public override toString(): string { return `- TriangleMesh\n  - Number of triangles: ${this.getNumTriangles()}\n  - Number of vertexes: ${this.getNumVertices()}\n`; }
  private interpolateTriangleData(index: number, out: RayHit, direction: Vector3Dd): void { const [a,b,c] = this.triangle(index); const p0=this.position(a), p1=this.position(b), p2=this.position(c); const q=out.p; const v0=p1.subtract(p0),v1=p2.subtract(p0),v2=q.subtract(p0); const d00=v0.dotProduct(v0),d01=v0.dotProduct(v1),d11=v1.dotProduct(v1),d20=v2.dotProduct(v0),d21=v2.dotProduct(v1),den=d00*d11-d01*d01; if (Math.abs(den)>0) { const w=(d00*d21-d01*d20)/den,u=(d11*d20-d01*d21)/den,v=1-u-w; if (this.vertexNormals !== null) out.n=this.vector(this.vertexNormals,a).multiply(v).add(this.vector(this.vertexNormals,b).multiply(u)).add(this.vector(this.vertexNormals,c).multiply(w)).normalized(); if (this.vertexUvs !== null) { out.u=this.vertexUvs[a*2]!*v+this.vertexUvs[b*2]!*u+this.vertexUvs[c*2]!*w; out.v=this.vertexUvs[a*2+1]!*v+this.vertexUvs[b*2+1]!*u+this.vertexUvs[c*2+1]!*w; } } if (out.n.dotProduct(direction)>=0) out.n=out.n.multiply(-1); }
  private fillMaterialAndTexture(triangle: number, out: RayHit): void { out.material=this.materials?.[0] ?? null; for (let i=0; this.materialRanges !== null && i<this.materialRanges.length-1;i++) if (triangle>=this.materialRanges[i]![0]!&&triangle<this.materialRanges[i+1]![0]!) { out.material=this.materials?.[this.materialRanges[i+1]![1]!] ?? null; break; } out.texture=null; for (let i=0; this.textureRanges !== null && i<this.textureRanges.length-1;i++) if (triangle>=this.textureRanges[i]![0]!&&triangle<this.textureRanges[i+1]![0]!) { out.texture=this.textures?.[this.textureRanges[i+1]![1]!-1] ?? null; break; } }
  private writeVertex(i: number, vertex: Vertex): void { this.setVector(this.vertexPositions!,i,vertex.position); if(this.vertexNormals!==null)this.setVector(this.vertexNormals,i,vertex.normal); if(this.vertexBinormals!==null)this.setVector(this.vertexBinormals,i,vertex.binormal); if(this.vertexTangents!==null)this.setVector(this.vertexTangents,i,vertex.tangent); if(this.vertexUvs!==null){this.vertexUvs[i*2]=vertex.u;this.vertexUvs[i*2+1]=vertex.v;} }
  private assertVertex(i: number): void { if (!Number.isInteger(i)||i<0||i>=this.getNumVertices()) throw new RangeError("Vertex index out of bounds"); } private position(i: number): Vector3Dd { this.assertVertex(i); return this.vector(this.vertexPositions!,i); } private vector(a: Float64Array,i: number): Vector3Dd{return new Vector3Dd(a[i*3]!,a[i*3+1]!,a[i*3+2]!);} private setVector(a: Float64Array,i: number,v: Vector3Dd):void{a[i*3]=v.x();a[i*3+1]=v.y();a[i*3+2]=v.z();} private triangle(i:number):[number,number,number]{if(this.triangleIndices===null||i<0||i>=this.getNumTriangles())throw new RangeError("Triangle index out of bounds");const n=i*3;return[this.triangleIndices[n]!,this.triangleIndices[n+1]!,this.triangleIndices[n+2]!];}
}
