/* Generated by Together */

package vitral.toolkits.common;

public class Triangle {
    private long point0;
    private long point1;
    private long point2;

    /**
     * @directed
     * @supplierRole normal
     * @supplierCardinality 0..1
     * @clientCardinality 1
     * @link aggregation*/
    private Vector3D normal;

    /**
     *
     */
    public Triangle()
    {
      point0 = 0;
      point1 = 0;
      point2 = 0;
    }

    /**
     *
     * @param point0 long
     * @param point1 long
     * @param point2 long
     */
    public Triangle(long point0, long point1, long point2)
    {
      this.point0 = point0;
      this.point1 = point1;
      this.point2 = point2;
    }

    /**
     *
     * @return long
     */
    public long getPoint0()
    {
      return this.point0;
    }

    /**
     *
     * @return long
     */
    public long getPoint1()
    {
      return this.point1;
    }

    /**
     *
     * @return long
     */
    public long getPoint2()
    {
      return this.point2;
    }

    /**
     *
     * @param point0 long
     */
    public void setPoint0(long point0)
    {
      this.point0 = point0;
    }

    /**
     *
     * @param point1 long
     */
    public void setPoint1(long point1)
    {
      this.point1 = point1;
    }

    /**
     *
     * @param point2 long
     */
    public void setPoint2(long point2)
    {
      this.point2 = point2;
    }
}
