/* Generated by Together */

package vitral.toolkits.common;

import net.java.games.jogl.GL;

public class Vertex {
    /**
     * @link aggregation
     * @clientCardinality 1
     * @supplierCardinality 1
     * @directed
     * @supplierRole position*/
    private Vector3D position;

    /**
     * @link aggregation
     * @directed
     * @supplierRole normal
     * @clientCardinality 1
     * @supplierCardinality 1
     */
    private Vector3D normal;

    /**
     * @link aggregation
     * @directed
     * @supplierRole binormal
     * @clientCardinality 1
     * @supplierCardinality 1
     */
    private Vector3D binormal;

    /**
     * @link aggregation
     * @directed
     * @supplierRole tangent
     * @clientCardinality 1
     * @supplierCardinality 1
     */
    private Vector3D tangent;

    private double u;
    private double v;

    /**
     * @directed
     * @supplierCardinality 0..*
     * @clientCardinality 1
     * @supplierRole incidentTriangles
     */
    private Triangle incidentTriangles;

    public Vertex()
    {
      position = new Vector3D();
      normal = new Vector3D();
      binormal = new Vector3D();
      tangent = new Vector3D();
      incidentTriangles = new Triangle();
      u = 0.0;
      v = 0.0;
    }

    public Vertex(Vector3D position)
    {
      this.position = position;
      normal = new Vector3D();
      binormal = new Vector3D();
      tangent = new Vector3D();
      incidentTriangles = new Triangle();
      u = 0.0;
      v = 0.0;

    }

    public Vertex(Vector3D position,Vector3D normal,Vector3D binormal,Vector3D tangent)
    {
      this.position = position;
      this.normal = normal;
      this.binormal = normal;
      this.tangent = tangent;
      incidentTriangles = new Triangle();
      u = 0.0;
      v = 0.0;
    }

    public Vertex(Vertex vertex)
    {
      this.position = vertex.getPosition();
      this.normal = vertex.getNormal();
      this.binormal = vertex.getBinormal();
      this.tangent = vertex.getTangent();
      this.u = vertex.getU();
      this.v = vertex.getV();
    }

    public Vector3D getPosition() {
        return this.position;
    }

    public Vector3D getNormal() {
        return this.normal;
    }

    public Vector3D getBinormal() {
        return this.binormal;
    }

    public Vector3D getTangent() {
        return this.tangent;
    }

    public double getU() {
        return this.u;
    }

    public double getV() {
        return this.v;
    }

    public void setPosition(Vector3D position) {
        this.position = position;
    }

    public void setNormal(Vector3D normal) {
        this.normal = normal;
    }

    public void setBinormal(Vector3D binormal) {
        this.binormal = binormal;
    }

    public void setTangent(Vector3D tangent) {
        this.tangent = tangent;
    }

    public void setU(double u) {
        this.u = u;
    }

    public void setV(double v) {
        this.v = v;
    }

    public void draw(GL gl) {
      gl.glNormal3d( normal.x, normal.y, normal.z );
      gl.glVertex3d( position.x , position.y, position.z );
      /** mas codigo despues **/
    }
}
