/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vsdk_toolkit_processing_SpharmonicKitWrapper */

#ifndef _Included_vsdk_toolkit_processing_SpharmonicKitWrapper
#define _Included_vsdk_toolkit_processing_SpharmonicKitWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vsdk_toolkit_processing_SpharmonicKitWrapper
 * Method:    executeSphericalHarmonics
 * Signature: ([B[D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_vsdk_toolkit_processing_SpharmonicKitWrapper_executeSphericalHarmonics
  (JNIEnv *, jclass, jbyteArray, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
