#ifndef __VSDK_TOOLKIT_RENDER_RAYTRACING_RASTERTILEGENERATIONSTRATEGY_H__
#define __VSDK_TOOLKIT_RENDER_RAYTRACING_RASTERTILEGENERATIONSTRATEGY_H__

enum class RasterTileGenerationStrategy {
    LINEAR,
    SERIAL
};

#endif
