import { HtmlWindow } from "./HtmlContainers.js";

/**
A folder or a file of the manifest of a server folder (see
`scripts/etc-index.mjs` of the web container): folders have children,
files have a size.
*/
interface HtmlFileIndexEntry {
    readonly name: string;
    readonly size?: number;
    readonly children?: readonly HtmlFileIndexEntry[];
}

/**
Suffix filter of an `HtmlFileChooser` (Swing's `FileFilter`).
*/
export class HtmlFileFilter {
    /**
    @param suffix accepted suffix, without the dot and in lower case
    @param description description of the kind of files, as shown to the user
    */
    public constructor(public readonly suffix: string, public readonly description: string) {}

    /**
    @param name name of a file
    @return true if it has the suffix of the filter
    */
    public accept(name: string): boolean {
        const i: number = name.lastIndexOf(".");
        return i > 0 && i < name.length - 1 && name.substring(i + 1).toLowerCase() === this.suffix;
    }
}

/**
A file chosen with an `HtmlFileChooser` to be read: a file of the server
(with its path) or a file of the user's computer.
*/
export class HtmlChosenFile {
    /**
    @param name name of the file
    @param path path (URL) of a server file, or null for a local one
    @param file local file, or null for a server one
    */
    public constructor(
        public readonly name: string,
        public readonly path: string | null,
        public readonly file: File | null,
    ) {}

    /**
    @return the folder of a server file (Java's `getParentFile()`), or null
    for a local file
    */
    public getParentPath(): string | null {
        if (this.path === null) {
            return null;
        }
        const i: number = this.path.lastIndexOf("/");
        return i > 0 ? this.path.substring(0, i) : ".";
    }

    /**
    @return the contents of the file
    */
    public async readBytes(): Promise<Uint8Array> {
        if (this.file !== null) {
            return new Uint8Array(await this.file.arrayBuffer());
        }
        const response: Response = await fetch(this.path!);
        if (!response.ok) {
            throw new Error("Cannot read \"" + this.path + "\": HTTP " + response.status);
        }
        return new Uint8Array(await response.arrayBuffer());
    }

    /**
    @return the contents of the file, as text (UTF-8)
    */
    public async readText(): Promise<string> {
        return new TextDecoder().decode(await this.readBytes());
    }
}

/**
Counterpart of Swing's `JFileChooser` for the DOM GUIs of the toolkit.

A page can not list the folders of its server, nor the ones of the user's
computer. So the chooser browses the folders of a server tree described by a
manifest (`index.json`, generated by the web container for its `etc` folder),
starting at a folder of it, and it also offers to pick a file of the user's
computer with the browser's own file chooser. Saving gives a file name: the
application hands the written file to the user as a download.
*/
export class HtmlFileChooser {
    private static readonly indexes: Map<string, Promise<HtmlFileIndexEntry | null>> =
        new Map<string, Promise<HtmlFileIndexEntry | null>>();

    private readonly filters: HtmlFileFilter[] = [];
    private currentDirectory: string;
    private readonly rootPath: string;

    /**
    @param currentDirectory folder shown first, as a path under `rootPath`
    (i.e. "./etc/geometry")
    @param rootPath path of the folder described by the manifest
    @param indexPath path of the manifest
    */
    public constructor(
        currentDirectory: string,
        rootPath: string = "./etc",
        private readonly indexPath: string = "./etc/index.json",
    ) {
        this.currentDirectory = HtmlFileChooser.normalize(currentDirectory);
        this.rootPath = HtmlFileChooser.normalize(rootPath);
    }

    /**
    Swing's `addChoosableFileFilter`.
    */
    public addChoosableFileFilter(filter: HtmlFileFilter): void {
        this.filters.push(filter);
    }

    /**
    Shows the chooser to pick a file to read.
    @param title title of the dialog
    @return the chosen file, or null if the user cancelled
    */
    public async showOpenDialog(title: string = "Open"): Promise<HtmlChosenFile | null> {
        const result: HtmlChosenFile | string | null = await this.showDialog(title, false, "");
        return result instanceof HtmlChosenFile ? result : null;
    }

    /**
    Shows the chooser to give the name of a file to write.
    @param title title of the dialog
    @param defaultName name proposed
    @return the name, or null if the user cancelled
    */
    public async showSaveDialog(title: string = "Save", defaultName: string = ""): Promise<string | null> {
        const result: HtmlChosenFile | string | null = await this.showDialog(title, true, defaultName);
        return typeof result === "string" ? result : null;
    }

    private static normalize(path: string): string {
        let p: string = path.replace(/\/+$/, "");
        const parts: string[] = [];
        for (const part of p.split("/")) {
            if (part === "..") {
                if (parts.length > 0 && parts[parts.length - 1] !== "." && parts[parts.length - 1] !== "..") {
                    parts.pop();
                    continue;
                }
            }
            if (part === "" && parts.length > 0) {
                continue;
            }
            parts.push(part);
        }
        p = parts.join("/");
        return p === "" ? "." : p;
    }

    private loadIndex(): Promise<HtmlFileIndexEntry | null> {
        let pending: Promise<HtmlFileIndexEntry | null> | undefined = HtmlFileChooser.indexes.get(this.indexPath);
        if (pending === undefined) {
            pending = fetch(this.indexPath)
                .then((response: Response): Promise<HtmlFileIndexEntry | null> =>
                    response.ok ? response.json() as Promise<HtmlFileIndexEntry> : Promise.resolve(null))
                .catch((): null => null);
            HtmlFileChooser.indexes.set(this.indexPath, pending);
        }
        return pending;
    }

    private folderAt(index: HtmlFileIndexEntry, path: string): HtmlFileIndexEntry | null {
        if (path === this.rootPath) {
            return index;
        }
        if (!path.startsWith(this.rootPath + "/")) {
            return null;
        }
        let folder: HtmlFileIndexEntry | undefined = index;
        for (const part of path.substring(this.rootPath.length + 1).split("/")) {
            folder = folder?.children?.find((entry: HtmlFileIndexEntry): boolean =>
                entry.name === part && entry.children !== undefined);
            if (folder === undefined) {
                return null;
            }
        }
        return folder;
    }

    private showDialog(title: string, save: boolean, defaultName: string): Promise<HtmlChosenFile | string | null> {
        return new Promise<HtmlChosenFile | string | null>((resolve): void => {
            const dialog: HtmlWindow = new HtmlWindow(title, true);
            let settled: boolean = false;
            const finish = (value: HtmlChosenFile | string | null): void => {
                if (settled) {
                    return;
                }
                settled = true;
                dialog.dispose();
                resolve(value);
            };
            dialog.addCloseListener((): void => finish(null));
            dialog.setSize(520, 420);

            const body: HTMLDivElement = document.createElement("div");
            body.className = "vitral-file-chooser";
            const pathLabel: HTMLDivElement = document.createElement("div");
            pathLabel.className = "vitral-file-chooser-path";
            const list: HTMLDivElement = document.createElement("div");
            list.className = "vitral-file-chooser-list";
            list.setAttribute("role", "listbox");
            const nameRow: HTMLDivElement = document.createElement("div");
            nameRow.className = "vitral-file-chooser-row";
            const nameLabel: HTMLLabelElement = document.createElement("label");
            nameLabel.textContent = "File name:";
            const nameField: HTMLInputElement = document.createElement("input");
            nameField.type = "text";
            nameField.className = "vitral-text-field";
            nameField.value = defaultName;
            nameRow.appendChild(nameLabel);
            nameRow.appendChild(nameField);

            const filterRow: HTMLDivElement = document.createElement("div");
            filterRow.className = "vitral-file-chooser-row";
            const filterLabel: HTMLLabelElement = document.createElement("label");
            filterLabel.textContent = "Files of type:";
            const filterSelect: HTMLSelectElement = document.createElement("select");
            filterSelect.className = "vitral-text-field";
            const allOption: HTMLOptionElement = document.createElement("option");
            allOption.value = "-1";
            allOption.textContent = "All files";
            for (let i: number = 0; i < this.filters.length; i++) {
                const option: HTMLOptionElement = document.createElement("option");
                option.value = String(i);
                option.textContent = this.filters[i]!.description + " (*." + this.filters[i]!.suffix + ")";
                filterSelect.appendChild(option);
            }
            filterSelect.appendChild(allOption);
            filterRow.appendChild(filterLabel);
            filterRow.appendChild(filterSelect);

            const buttons: HTMLDivElement = document.createElement("div");
            buttons.className = "vitral-file-chooser-buttons";
            const local: HTMLButtonElement = HtmlFileChooser.button(save ? "" : "Local file...");
            const accept: HTMLButtonElement = HtmlFileChooser.button(save ? "Save" : "Open");
            const cancel: HTMLButtonElement = HtmlFileChooser.button("Cancel");
            if (!save) {
                buttons.appendChild(local);
            }
            buttons.appendChild(accept);
            buttons.appendChild(cancel);

            body.appendChild(pathLabel);
            body.appendChild(list);
            body.appendChild(nameRow);
            body.appendChild(filterRow);
            body.appendChild(buttons);
            dialog.content.appendChild(body);

            const localInput: HTMLInputElement = document.createElement("input");
            localInput.type = "file";
            localInput.hidden = true;
            body.appendChild(localInput);

            const currentFilter = (): HtmlFileFilter | null => {
                const index: number = Number(filterSelect.value);
                return index >= 0 ? this.filters[index] ?? null : null;
            };
            const render = async (): Promise<void> => {
                const index: HtmlFileIndexEntry | null = await this.loadIndex();
                pathLabel.textContent = this.currentDirectory;
                list.replaceChildren();
                const folder: HtmlFileIndexEntry | null = index !== null ? this.folderAt(index, this.currentDirectory) : null;
                if (folder === null) {
                    const empty: HTMLDivElement = document.createElement("div");
                    empty.textContent = "(this folder can not be browsed)";
                    list.appendChild(empty);
                    return;
                }
                const filter: HtmlFileFilter | null = currentFilter();
                if (this.currentDirectory !== this.rootPath) {
                    list.appendChild(this.entryElement("..", true, (): void => {
                        this.currentDirectory = HtmlFileChooser.normalize(this.currentDirectory + "/..");
                        void render();
                    }, null));
                }
                for (const entry of folder.children ?? []) {
                    const isFolder: boolean = entry.children !== undefined;
                    if (!isFolder && filter !== null && !filter.accept(entry.name)) {
                        continue;
                    }
                    list.appendChild(this.entryElement(entry.name, isFolder, (): void => {
                        if (isFolder) {
                            this.currentDirectory = this.currentDirectory + "/" + entry.name;
                            void render();
                        }
                        else {
                            nameField.value = entry.name;
                            if (!save) {
                                finish(new HtmlChosenFile(entry.name, this.currentDirectory + "/" + entry.name, null));
                            }
                        }
                    }, (): void => {
                        if (!isFolder) {
                            nameField.value = entry.name;
                        }
                    }));
                }
            };
            filterSelect.addEventListener("change", (): void => {
                void render();
            });
            local.addEventListener("click", (): void => {
                const filter: HtmlFileFilter | null = currentFilter();
                localInput.accept = filter !== null ? "." + filter.suffix : "";
                localInput.click();
            });
            localInput.addEventListener("change", (): void => {
                const file: File | undefined = localInput.files?.[0];
                if (file !== undefined) {
                    finish(new HtmlChosenFile(file.name, null, file));
                }
            });
            accept.addEventListener("click", (): void => {
                const name: string = nameField.value.trim();
                if (name.length === 0) {
                    return;
                }
                finish(save ? name : new HtmlChosenFile(name, this.currentDirectory + "/" + name, null));
            });
            cancel.addEventListener("click", (): void => finish(null));
            nameField.addEventListener("keydown", (event: KeyboardEvent): void => {
                event.stopPropagation();
                if (event.key === "Enter") {
                    accept.click();
                }
                else if (event.key === "Escape") {
                    finish(null);
                }
            });

            dialog.setVisible(true);
            nameField.focus();
            void render();
        });
    }

    private entryElement(name: string, folder: boolean, open: () => void, select: (() => void) | null): HTMLElement {
        const element: HTMLDivElement = document.createElement("div");
        element.className = "vitral-file-chooser-entry" + (folder ? " vitral-file-chooser-folder" : "");
        element.setAttribute("role", "option");
        element.textContent = name;
        element.addEventListener("dblclick", open);
        element.addEventListener("click", (): void => {
            for (const sibling of Array.from(element.parentElement?.children ?? [])) {
                sibling.classList.remove("vitral-file-chooser-entry-selected");
            }
            element.classList.add("vitral-file-chooser-entry-selected");
            if (folder) {
                open();
            }
            else if (select !== null) {
                select();
            }
        });
        return element;
    }

    private static button(text: string): HTMLButtonElement {
        const b: HTMLButtonElement = document.createElement("button");
        b.type = "button";
        b.className = "vitral-button";
        b.textContent = text;
        return b;
    }
}

/**
Hands a written file to the user as a download: what a page can do where a
desktop application writes a file of its file system.
@param name name proposed for the file
@param data contents of the file
@param mimeType type of the contents
*/
export function downloadFile(name: string, data: Uint8Array | string, mimeType: string = "application/octet-stream"): void {
    const blob: Blob = new Blob([data as BlobPart], { type: mimeType });
    const url: string = URL.createObjectURL(blob);
    const anchor: HTMLAnchorElement = document.createElement("a");
    anchor.href = url;
    anchor.download = name.substring(name.lastIndexOf("/") + 1);
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    setTimeout((): void => URL.revokeObjectURL(url), 10000);
}
