//===========================================================================
//=-------------------------------------------------------------------------=
//= Module history:                                                         =
//= - May 4 2006 - Gina Chiquillo: Original base version                    =
//= - May 5 2006 - Oscar Chavarro: quality check                            =
//===========================================================================

package vsdk.toolkit.io.geometry;

import java.io.File;
import java.io.IOException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.Source;
import javax.xml.transform.Result;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerFactoryConfigurationError;

import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;

import vsdk.toolkit.common.Vector3D;
import vsdk.toolkit.environment.geometry.ParametricCubicCurve;

public class ParametricCubicCurvePersistence {
    private static final String[] nodesNames = {
        "Point",
        "Vector3D",
    };
    private static final String curveAttributesNames[] = 
        {"approximationSteps"};
    private static final String pointAttributesNames[] = 
        {"type"};

    public static ParametricCubicCurve importXml(String fileNameIn) {
        Document document;
        NodeList nodeList;

        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        factory.setValidating(true);
        factory.setNamespaceAware(true);

        try {
            DocumentBuilder builder = factory.newDocumentBuilder();
            document = builder.parse(new File(fileNameIn));

            nodeList = document.getElementsByTagName(nodesNames[0]);
            ParametricCubicCurve curve = nodeListToParametricCubicCurve(nodeList);
            NamedNodeMap atts = document.getFirstChild().getAttributes();
            if (atts != null) {
                Node atributo;
                atributo = atts.getNamedItem(curveAttributesNames[0]);
                String approximationSteps = atributo.getNodeValue();
                if ( !"".equals(approximationSteps) ) {
                    curve.setApproximationSteps(
                        Integer.parseInt(approximationSteps));
                }
            }
            return curve;
            // Se usan los errores de SAX
        }
        catch (SAXParseException spe) {
            // Error generated by the parser
            System.err.println("\n** Parsing error"
                               + ", line " + spe.getLineNumber()
                               + ", uri " + spe.getSystemId());
            System.err.println("   " + spe.getMessage());

            // Use the contained exception, if any
            Exception x = spe;
            if (spe.getException() != null) {
                x = spe.getException();
            }
            x.printStackTrace();

        }
        catch (SAXException sxe) {
            // Error generated during parsing
            Exception x = sxe;
            if (sxe.getException() != null) {
                x = sxe.getException();
            }
            x.printStackTrace();

        }
        catch (ParserConfigurationException pce) {
            // Parser with specified options can't be built
            pce.printStackTrace();

        }
        catch (IOException ioe) {
            // I/O error
            ioe.printStackTrace();
        }
        return null;
    }

    public static ParametricCubicCurve 
    nodeListToParametricCubicCurve(NodeList nodeList) {
        ParametricCubicCurve curve = new ParametricCubicCurve();

        for ( int i = 0; i < nodeList.getLength(); i++ ) {

            Node nodo;
            nodo = nodeList.item(i);

            NodeList subNodos = nodo.getChildNodes();
            Vector3D v3[] = new Vector3D[3];
            int pos = 0;
            for (int j = 0; j < subNodos.getLength() - 1; j++) {
                Node subNodo = subNodos.item(j);
                if (subNodo.getLocalName() != null &&
                    subNodo.getLocalName().equals(nodesNames[1])) {
                    Node subNodo2 = subNodo.getFirstChild();

                    String coors[] = subNodo2.getNodeValue().trim().split(" ");
                    v3[pos] = new Vector3D(Double.parseDouble(coors[0]),
                                           Double.parseDouble(coors[1]),
                                           Double.parseDouble(coors[2]));
                    pos++;
                }
            }

            NamedNodeMap atts = nodo.getAttributes();
            Node atributo = atts.getNamedItem(pointAttributesNames[0]);
            String type = atributo.getNodeValue();
            if (!"".equals(type)) {
                curve.addPoint(v3, Integer.parseInt(type));
            }

        }
        return curve;
    }

    public static Element exportXml(ParametricCubicCurve curve,
                                    String fileName,
                                    String dtdFilename) {
        Document document;

        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            factory.setValidating(true);
            factory.setNamespaceAware(true);
            DocumentBuilder builder = null;
            builder = factory.newDocumentBuilder();
            document = builder.newDocument();
            Element nodeRoot = toElement(curve, document);
            document.appendChild(nodeRoot);
            document.normalizeDocument();

            // Prepare the output file
            Source source = new DOMSource(document);
            File file = new File(fileName);
            Result result = new StreamResult(file);

            // Write the DOM document to the file
            Transformer xformer = null;
            xformer = TransformerFactory.newInstance().newTransformer();
            xformer.setOutputProperty(OutputKeys.DOCTYPE_SYSTEM,
                                      dtdFilename);
            xformer.transform(source, result);
            document = builder.parse(file);
            return nodeRoot;
        }
        catch (ParserConfigurationException ex) {
            System.err.print("Exception: " + ex);
        }
        catch (TransformerFactoryConfigurationError ex1) {
            System.err.print("Exception: " + ex1);
        }
        catch (TransformerConfigurationException ex1) {
            System.err.print("Exception: " + ex1);
        }
        catch (TransformerException ex2) {
            System.err.print("Exception: " + ex2);
        }
        catch (IOException ex3) {
            System.err.print("Exception: " + ex3);
        }
        catch (SAXException ex3) {
            System.err.print("Exception: " + ex3);
        }
        return null;
    }

    public static Element toElement(ParametricCubicCurve curve,
                                    Document document) {
        Element nodeCurve = document.createElement("ParametricCubicCurve");
        try {

            nodeCurve.setAttribute(curveAttributesNames[0],
                                   "" + curve.getApproximationSteps());
            for (int i = 0; i < curve.getPointSize(); i++) {
                Element ePoint = document.createElement(nodesNames[0]);
                ePoint.setAttribute(pointAttributesNames[0], curve.types.get(i) + "");
                Vector3D v3[] = curve.getPoint(i);
                for (int j = 0; j < v3.length; j++) {
                    Element eVector = document.createElement(nodesNames[1]);
                    Vector3D v = v3[j];
                    eVector.setTextContent(v.x + " " + v.y + " " + v.z);
                    ePoint.appendChild(eVector);
                }
                nodeCurve.appendChild(ePoint);
            }
        }

        catch (TransformerFactoryConfigurationError ex1) {
            System.err.print("Exception: " + ex1);
        }

        return nodeCurve;
    }
}

//===========================================================================
//= EOF                                                                     =
//===========================================================================
