//===========================================================================
//=-------------------------------------------------------------------------=
//= Module history:                                                         =
//= - May 4 2006 - Gina Chiquillo: Original base version                    =
//= - May 5 2006 - Oscar Chavarro: quality check                            =
//===========================================================================

package vsdk.toolkit.io.geometry;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.FactoryConfigurationError;
import javax.xml.parsers.ParserConfigurationException;

import org.xml.sax.SAXException;
import org.xml.sax.SAXParseException;

import java.io.*;

import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.w3c.dom.NamedNodeMap;
import org.w3c.dom.Document;
import vsdk.toolkit.environment.geometry.ParametricBiCubicPatch;
import vsdk.toolkit.common.Vector3D;
import org.w3c.dom.Element;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.Source;
import javax.xml.transform.Result;
import javax.xml.transform.Transformer;
import javax.xml.transform.*;
import javax.xml.transform.*;

public class ParametricBiCubicPatchPersistence {
    private static String rootName = "ParametricBiCubicPatch";
    private static String patchAttributesNames[] = {
        "type", "approximationSteps"};
    private final static String[] nodesNames = {
        "ParametricCubicCurve",
        "Point"
    };

    public static ParametricBiCubicPatch importXml(String fileNameIn) {
        Document document;
        NodeList nodeList;

        DocumentBuilderFactory factory =DocumentBuilderFactory.newInstance();
        factory.setValidating(true);
        factory.setNamespaceAware(true);

        try {

            DocumentBuilder builder = factory.newDocumentBuilder();
            document = builder.parse(new File(fileNameIn));
            ParametricBiCubicPatch patch = null;
            Node nodeRoot=document.getElementsByTagName(rootName).item(0);

            NamedNodeMap atts = nodeRoot.getAttributes();
            if (atts != null) {
                Node atributo;
                atributo = atts.getNamedItem(patchAttributesNames[0]);
                String type = atributo.getNodeValue();
                if (!"".equals(type)) {
                    patch = new ParametricBiCubicPatch(Integer.parseInt(type));
                    atributo = atts.getNamedItem(patchAttributesNames[1]);
                    if(atributo!=null){
                        String approximationSteps = atributo.getNodeValue();
                        if (!"".equals(approximationSteps)) {
                            patch.setApproximationSteps(Integer.parseInt(approximationSteps));
                        }
                    }
                    nodeList = document.getElementsByTagName(nodesNames[1]);
                    patch.contourCurve = ParametricCubicCurvePersistence.nodeListToParametricCubicCurve(nodeList);

                }
            }

            return patch;
            // Se usan los errores de SAX
        }
        catch (SAXParseException spe) {

            // Error generated by the parser
            System.out.println("\n** Parsing error"
                               + ", line " + spe.getLineNumber()
                               + ", uri " + spe.getSystemId());
            System.out.println("   " + spe.getMessage());

            // Use the contained exception, if any
            Exception x = spe;
            if (spe.getException() != null) {
                x = spe.getException();
            }
            x.printStackTrace();

        }
        catch (SAXException sxe) {
            // Error generated during parsing
            Exception x = sxe;
            if (sxe.getException() != null) {
                x = sxe.getException();
            }
            x.printStackTrace();

        }
        catch (ParserConfigurationException pce) {
            // Parser with specified options can't be built
            pce.printStackTrace();

        }
        catch (IOException ioe) {
            // I/O error
            ioe.printStackTrace();
        }
        return null;
    }

    public static void exportXml(ParametricBiCubicPatch patch,
                                 String fileName, String dtdFilename) {
        Document document;
        try {

            DocumentBuilderFactory factory;

            factory = DocumentBuilderFactory.newInstance();
            factory.setValidating(true);
            factory.setNamespaceAware(true);
            DocumentBuilder builder = null;
            builder = factory.newDocumentBuilder();
            document = builder.newDocument();
            Element nodeRoot = document.createElement(rootName);


            nodeRoot.setAttribute(patchAttributesNames[1],
                                  "" + patch.getApproximationSteps());
            nodeRoot.setAttribute(patchAttributesNames[0],
                                  "" + patch.getType());

            Element eCurve;

            eCurve = ParametricCubicCurvePersistence.toElement(patch.contourCurve, document);

            nodeRoot.appendChild(eCurve);

            document.appendChild(nodeRoot);
            document.normalizeDocument();

            // Prepare the output file
            Source source = new DOMSource(document);
            File file = new File(fileName);
            Result result = new StreamResult(file);

            // Write the DOM document to the file
            Transformer xformer = null;
            xformer = TransformerFactory.newInstance().newTransformer();
            xformer.setOutputProperty(OutputKeys.DOCTYPE_SYSTEM,
                                      dtdFilename);
            xformer.transform(source, result);
            document = builder.parse(file);

        }
        catch (ParserConfigurationException ex) {
            System.err.print("Exception: " + ex);
        }
        catch (TransformerFactoryConfigurationError ex1) {
            System.err.print("Exception: " + ex1);
        }
        catch (TransformerConfigurationException ex1) {
            System.err.print("Exception: " + ex1);
        }
        catch (TransformerException ex2) {
            System.err.print("Exception: " + ex2);
        }
        catch (IOException ex3) {
            System.err.print("Exception: " + ex3);
        }
        catch (SAXException ex3) {
            System.err.print("Exception: " + ex3);
        }
    }

}

//===========================================================================
//= EOF                                                                     =
//===========================================================================
